image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Install Python deps (including JupyterLab)
      pip install --no-cache-dir -r requirements.txt
    command: |
      # Launch JupyterLab
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

ports:
  - port: 8888
    onOpen: open-preview
